// src/constants/dbSchema.js

export const TABLES = {
  VENDORS: "vendor_request",
  USER: "user",
  DELIVERY_ADDRESS: "delivery_address",
  CUSION_CATEGORY: "cuisine_category",
  USER_SEARCHES: "user_searches",
  ORDERS: "orders",
  RATING: "rating",
  TRANSACTION: "transaction",
  ORDER_ITEM: "order_item",
  CART_ITEM: "cart_item",
  USER_CART: "user_cart",
  SELECTED_ADDRESS: "selected_address",
  COMPLETED_ORDERS: "completed_orders",
  ITEM_CATEGORY: "item_category",
  CATEGORY_CREATED_BY_VENDOR: "category_created_by_vendor",
  OFFER_BANNER: "offer_banner",
  DELIVERY_PARTNER: "delivery_partner",
  ITEM: "item",
  ITEM_RATINGS: "item_ratings",
};

export const COLUMNS = {
  VENDOR: {
    ID: "v_id",
    V_NAME: "v_name",
    U_ID: "u_id",
    WARNING: "warning",
    BLOCKED: "blocked",
    SHOP_NAME: "shop_name",
    CREATED_AT: "created_at",
    UPADATED_AT: "updated_at",
    BANNER_URL: "banner_url",
    SHIFT1_OPENING_TIME: "shift1_opening_time",
    SHIFT1_CLOSING_TIME: "shift1_closing_time",
    SHIFT2_OPENING_TIME: "shift2_opening_time",
    SHIFT2_CLOSING_TIME: "shift2_closing_time",
    DISCOUNT: "discount_available",
    LATITUDE: "latitude",
    LONGITUDE: "longitude",
    REQUEST_STATUS: "request_status",
    REJECTION_REASON: "rejection_reason",
    VIDEO_URL: "video_url",
    RATING: "rating",
    EXPECTED_DELIVERY_TIME: "expected_dt_ms",
    APPROVED_BY: "approved_by",
    STATUS: "status",
    NOTE_FROM_VENDOR: "note_from_vendor",
    PAYMENT_URL: "payment_url",
    RATING_COUNT: "rating_count",
    CITY: "city",
    STATE: "state",
    STREET: "street",
    PINCODE: "pincode",
    MOBILE: "mobile_number",
    AVAILABLE: "available",
    CUISINES: "cuisines_available",
    LOCATION: "location",
  },
  USER: {
    CREATED_AT: "created_at",
    NAME: "name",
    MOBILE_NUMBER: "mobile_number",
    BLOCKED: "blocked",
    INCOME_RANGE: "income_range",
    UPDATED_AT: "updated_at",
    WALLET_BALANCE: "wallet_balance",
    WARNING: "warning",
    REFERRED_BY: "referred_by",
    RATING: "rating",
    DP_URL: "dp_url",
    PROFESSION: "profession",
    ROLE: "role",
    USER_ID: "user_id",
    REFERRAL_CODE: "referral_code",
    IS_ADMIN: "is_admin",
  },

  ORDERS: {
    ORDER_ID: "order_id",
    CREATED_TS: "created_ts",
    U_ID: "u_id",
    UPDATED_TS: "updated_ts",
    ADDR_ID: "addr_id",
    TOTAL_AMOUNT: "total_amount",
    DISCOUNTED_AMOUNT: "discounted_amount",
    WALLET_BALANCE_USED: "wallet_balance_used",
    PAYMENT_ID: "payment_id",
    TAX_COLLECTED: "tax_collected",
    STATUS: "status",
    T_ID: "t_id",
    PAYMENT_MODE: "payment_mode",
    V_ID: "v_id",
    DELIVERY_TYPE: "delivery_type",
    USER_LAT: "user_lat",
    USER_LONG: "user_long",
    VENDOR_LAT: "vendor_lat",
    VENDOR_LONG: "vendor_long",
    DELIVERY_FEE: "delivery_fee",
    USER_ORDER_ID: "user_order_id",
    DP_OTP: "dp_otp",
    DP_ID: "dp_id",
    USER_OTP: "user_otp",
    EXPECTED_DT_MS: "expected_dt_ms",
    GROUP_ID: "group_id",
    GROUP_SEQ_NO: "group_seq_no",
    IS_FULLY_INSERTED: "is_fully_inserted",
    ACCEPTED_TS: "accepted_ts",
    PREPARING_TS: "preparing_ts",
    PREPARED_TS: "prepared_ts",
    ON_THE_WAY_TS: "on_the_way_ts",
    DELIVERED_TS: "delivered_ts",
    VENDOR_DISCOUNT: "vendor_discount",
    PLATFORM_FEE: "platform_fee",
  },

  DELIVERY_ADDRESS: {
    ADDRESS_ID: "address_id",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    USER_ID: "u_id",
    LAT: "lat",
    LONG: "long",
    HOUSE_NO: "h_no",
    LANDMARK: "landmark",
    CONTACT_NO: "contact_no",
    ADDITIONAL_DETAILS: "additional_details",
    ADDRESS_TYPE: "address_type",
    IS_SELECTED: "is_selected",
    IS_DELETED: "is_deleted",
    SEARCH_TEXT: "search_text",
  },

  SELECTED_ADDRESS: {
    SA_ID: "sa_id",
    CREATED_AT: "created_at",
    UPDATED_AT: "updated_at",
    USER_ID: "user_id",
    LAT: "lat",
    LONG: "long",
    HOUSE_NO: "h_no",
    LANDMARK: "landmark",
    CONTACT_NO: "contact_no",
    ADDITIONAL_DETAILS: "additional_details",
    ADDRESS_TYPE: "address_type",
    ADDRESS_ID: "address_id",
  },
};

export const ORDER_STATUS = {
  PENDING: "pending",
  ACCEPTED: "accepted",
  PREPARING: "preparing",
  PREPARED: "prepared",
  ON_THE_WAY: "on the way",
  DELIVERED: "delivered",
  CANCELED: "canceled",
  FAILED: "failed",
};
